# Generated by Django 6.0 on 2025-12-21 09:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutputProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('video_mode', models.CharField(choices=[('copy', 'Copy (no re-encode)'), ('encode', 'Encode (re-encode)')], default='copy', max_length=20)),
                ('encoder_preference', models.CharField(choices=[('auto', 'Auto (NVENC → QSV → CPU)'), ('nvidia_first', 'NVIDIA first (NVENC → QSV → CPU)'), ('intel_first', 'Intel first (QSV → NVENC → CPU)'), ('cpu_only', 'CPU only')], default='auto', help_text='Used in Phase 4 for NVENC/QSV/CPU fallback. In Phase 3, ENCODE uses CPU (libx264).', max_length=30)),
                ('realtime_input', models.BooleanField(default=False, help_text="For FILE inputs, add -re to pace input in real-time (recommended for 'live file playback').")),
                ('loop_input', models.BooleanField(default=False, help_text='For FILE inputs, add -stream_loop -1 to loop indefinitely.')),
                ('video_codec', models.CharField(blank=True, default='libx264', help_text='When encoding video, e.g. libx264', max_length=50)),
                ('audio_mode', models.CharField(choices=[('copy', 'Copy (no re-encode)'), ('encode', 'Encode (re-encode)'), ('disable', 'Disable (no audio)')], default='copy', max_length=20)),
                ('audio_codec', models.CharField(blank=True, default='aac', help_text='When encoding audio, e.g. aac', max_length=50)),
                ('default_pkt_size', models.PositiveIntegerField(blank=True, help_text='Default pkt_size for UDP output (e.g. 1316).', null=True)),
                ('default_overrun_nonfatal', models.BooleanField(default=True, help_text='Default overrun_nonfatal=1 for UDP outputs.')),
                ('default_ttl', models.PositiveIntegerField(blank=True, help_text='Default TTL for multicast outputs (optional).', null=True, validators=[django.core.validators.MaxValueValidator(255)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_test_channel', models.BooleanField(db_index=True, default=False, help_text='Marks a channel as an internal test channel (created from admin tools).')),
                ('enabled', models.BooleanField(default=True, help_text='If off, enforcer will not run this channel.')),
                ('input_type', models.CharField(choices=[('udp_multicast', 'UDP Multicast (MPEG-TS)'), ('rtsp', 'RTSP'), ('rtmp', 'RTMP'), ('file', 'File'), ('internal_gen', 'Internal Generator (Test)')], default='udp_multicast', max_length=20)),
                ('input_url', models.CharField(default='udp://@239.0.0.1:5000', help_text='For multicast: e.g. udp://@239.10.10.10:5001 (fifo_size & overrun options may be added automatically). For Internal Generator, this can be internal://generator.', max_length=512)),
                ('multicast_interface', models.CharField(blank=True, default='', help_text='Optional: network interface/IP for multicast receiving (advanced usage).', max_length=64)),
                ('output_type', models.CharField(choices=[('udp_ts', 'UDP TS Unicast'), ('hls', 'HLS (m3u8)'), ('rtmp', 'RTMP'), ('file_ts', 'File (TS)'), ('file_mp4', 'File (MP4)')], default='udp_ts', max_length=20)),
                ('output_target', models.CharField(default='udp://127.0.0.1:5002', help_text='Destination for the channel output.\n\n✅ Unicast (send to one receiver):\n  udp://10.120.0.111:5000?pkt_size=1316\n\n✅ Multicast (send to many receivers):\n  udp://239.0.0.1:5000?pkt_size=1316&ttl=16\n\nNotes:\n• You can enter a multicast group (239.x/232.x) even if you think of it as “unicast mode” — it’s still the same UDP-TS output; only the destination IP changes.\n• Useful options: pkt_size=1316, ttl=… (multicast), localaddr=… (force interface, helpful on Windows).\n', max_length=512)),
                ('playback_tail_enabled', models.BooleanField(default=False, help_text='If enabled: when schedule ends, recording stops immediately but playback continues until (schedule_end + delay). Useful to flush the delayed buffer.')),
                ('recording_path_template', models.CharField(default='recordings/{channel}/{date}/', help_text='Recording path. Relative paths are under MEDIA_ROOT. Use {channel}, {date}, {time} placeholders.', max_length=512)),
                ('recording_segment_minutes', models.PositiveIntegerField(default=60, help_text='Length of each recording segment in minutes.')),
                ('auto_delete_enabled', models.BooleanField(default=False, help_text='If enabled, old recording segments will be deleted automatically.')),
                ('auto_delete_after_segments', models.PositiveIntegerField(blank=True, help_text='Keep last N segments. Leave blank to ignore.', null=True)),
                ('auto_delete_after_days', models.PositiveIntegerField(blank=True, help_text='Delete segments older than N days. Leave blank to ignore.', null=True)),
                ('video_mode', models.CharField(choices=[('copy', 'Copy (no re-encode)'), ('encode', 'Encode (re-encode)')], default='copy', max_length=20)),
                ('video_codec', models.CharField(blank=True, default='', help_text='When encoding video, e.g. libx264', max_length=50)),
                ('audio_mode', models.CharField(choices=[('copy', 'Copy (no re-encode)'), ('encode', 'Encode (re-encode)'), ('disable', 'Disable (no audio)')], default='copy', max_length=20)),
                ('audio_codec', models.CharField(blank=True, default='', help_text='When encoding audio, e.g. aac', max_length=50)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, help_text='Local start time. If blank, treated as 00:00.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Local end time. If blank, treated as 00:00. If start == end -> full day.', null=True)),
                ('date_from', models.DateField(blank=True, help_text='First active date (inclusive).', null=True)),
                ('date_to', models.DateField(blank=True, help_text='Last active date (inclusive).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_profile', models.ForeignKey(blank=True, help_text='Defines how the stream is produced (COPY vs ENCODE). New channels default to COPY.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='transcoder.outputprofile')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OutputTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Target', max_length=80)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('process_pid', models.IntegerField(blank=True, editable=False, null=True)),
                ('protocol', models.CharField(default='udp_mpegts', help_text='Future: srt/hls/etc. Phase 1-4 uses udp_mpegts.', max_length=40)),
                ('target_url', models.CharField(help_text='e.g. udp://192.168.1.26:5002', max_length=500)),
                ('pkt_size', models.PositiveIntegerField(blank=True, null=True)),
                ('overrun_nonfatal', models.BooleanField(blank=True, help_text='Override overrun_nonfatal (1/0). Leave blank to inherit profile default.', null=True)),
                ('fifo_size', models.PositiveIntegerField(blank=True, null=True)),
                ('buffer_size', models.PositiveIntegerField(blank=True, null=True)),
                ('ttl', models.PositiveIntegerField(blank=True, help_text='TTL for multicast (optional).', null=True, validators=[django.core.validators.MaxValueValidator(255)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_targets', to='transcoder.channel')),
            ],
            options={
                'ordering': ['channel_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimeShiftProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('delay_seconds', models.PositiveIntegerField(default=0, help_text='Delay in seconds (0..86400). 0 = LIVE mode (no recording, direct restream from input to output). >0 = Time-shift mode (records to disk then plays back with this delay).', validators=[django.core.validators.MaxValueValidator(86400)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeshift_profile', to='transcoder.channel')),
            ],
            options={
                'verbose_name': 'Time-shift profile',
                'verbose_name_plural': 'Time-shift profiles',
            },
        ),
    ]
