# Generated by Django 6.0 on 2025-12-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='audio_codec',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='audio_mode',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='video_codec',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='video_mode',
        ),
    ]
