# Generated by Django 6.0 on 2025-12-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0003_backfill_outputtargets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='output_target',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='output_type',
        ),
    ]
