# Generated by Django 6.0 on 2025-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0004_remove_channel_output_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputprofile',
            name='audio_bitrate_k',
            field=models.PositiveIntegerField(blank=True, help_text='Audio bitrate in kbits (e.g. 128). Only used when audio_mode=ENCODE.', null=True),
        ),
        migrations.AddField(
            model_name='outputprofile',
            name='fps_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Optional output FPS cap (e.g. 25). Only used when encoding.', null=True),
        ),
        migrations.AddField(
            model_name='outputprofile',
            name='gop_size',
            field=models.PositiveIntegerField(blank=True, help_text='GOP size (e.g. 50 for 25fps). Only used when encoding.', null=True),
        ),
        migrations.AddField(
            model_name='outputprofile',
            name='scale_height',
            field=models.PositiveIntegerField(blank=True, help_text='Optional scale height (must set width too). Only used when encoding.', null=True),
        ),
        migrations.AddField(
            model_name='outputprofile',
            name='scale_width',
            field=models.PositiveIntegerField(blank=True, help_text='Optional scale width (must set height too). Only used when encoding.', null=True),
        ),
        migrations.AddField(
            model_name='outputprofile',
            name='video_bitrate_k',
            field=models.PositiveIntegerField(blank=True, help_text='Target video bitrate in kbits (e.g. 2500). Only used when video_mode=ENCODE.', null=True),
        ),
        migrations.AddField(
            model_name='outputprofile',
            name='video_bufsize_k',
            field=models.PositiveIntegerField(blank=True, help_text='Optional bufsize in kbits for VBV (e.g. 6000). Only used when video_mode=ENCODE.', null=True),
        ),
        migrations.AddField(
            model_name='outputprofile',
            name='video_maxrate_k',
            field=models.PositiveIntegerField(blank=True, help_text='Optional maxrate in kbits for VBV (e.g. 3000). Only used when video_mode=ENCODE.', null=True),
        ),
        migrations.AddField(
            model_name='outputprofile',
            name='x264_preset',
            field=models.CharField(blank=True, default='veryfast', help_text='x264 preset (e.g. veryfast, faster, fast). Only used for libx264.', max_length=30),
        ),
        migrations.AddField(
            model_name='outputprofile',
            name='x264_tune',
            field=models.CharField(blank=True, default='zerolatency', help_text='x264 tune (e.g. zerolatency). Only used for libx264 and UDP live use.', max_length=30),
        ),
    ]
