# Generated by Django 6.0 on 2025-12-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0005_outputprofile_audio_bitrate_k_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputprofile',
            name='x264_preset',
            field=models.CharField(choices=[('ultrafast', 'ultrafast'), ('superfast', 'superfast'), ('veryfast', 'veryfast'), ('faster', 'faster'), ('fast', 'fast'), ('medium', 'medium'), ('slow', 'slow'), ('slower', 'slower'), ('veryslow', 'veryslow')], default='veryfast', help_text='x264 preset. Recommended: veryfast (good default), faster/fast (better quality), superfast/ultrafast (lowest CPU). Used only when video_codec=libx264.', max_length=30),
        ),
        migrations.AlterField(
            model_name='outputprofile',
            name='x264_tune',
            field=models.CharField(choices=[('zerolatency', 'zerolatency'), ('fastdecode', 'fastdecode'), ('film', 'film'), ('animation', 'animation'), ('grain', 'grain'), ('stillimage', 'stillimage')], default='zerolatency', help_text='x264 tune. Recommended for live UDP: zerolatency. Used only when video_codec=libx264.', max_length=30),
        ),
    ]
