# Generated by Django 6.0 on 2025-12-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcoder', '0006_alter_outputprofile_x264_preset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputtarget',
            name='buffer_size',
            field=models.PositiveIntegerField(blank=True, help_text='Socket buffer size for UDP output.\n\nOnly needed for high-bitrate or unstable networks.\nLeave blank to use system defaults.', null=True),
        ),
        migrations.AlterField(
            model_name='outputtarget',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable this output target. If disabled, FFmpeg will NOT send any stream to this target.'),
        ),
        migrations.AlterField(
            model_name='outputtarget',
            name='fifo_size',
            field=models.PositiveIntegerField(blank=True, help_text='Size of FFmpeg UDP FIFO buffer.\n\nUse this only if you experience packet drops.\nExample values: 1000000 – 5000000\n\nLeave blank for FFmpeg default.', null=True),
        ),
        migrations.AlterField(
            model_name='outputtarget',
            name='overrun_nonfatal',
            field=models.BooleanField(blank=True, help_text='Controls FFmpeg behavior when the UDP send buffer overflows.\n\n• Yes (1): Continue streaming even if packets are dropped (recommended)\n• No (0): Stop FFmpeg on buffer overrun\n• Blank: Inherit from OutputProfile default', null=True),
        ),
        migrations.AlterField(
            model_name='outputtarget',
            name='pkt_size',
            field=models.PositiveIntegerField(blank=True, help_text='UDP packet size in bytes.\n\nRecommended:\n• 1316 (best for MPEG-TS over UDP)\n\nLeave blank to inherit the OutputProfile default.', null=True),
        ),
        migrations.AlterField(
            model_name='outputtarget',
            name='protocol',
            field=models.CharField(choices=[('udp_mpegts', 'UDP MPEG-TS')], default='udp_mpegts', help_text='Streaming protocol used for this target.\n\nCurrently supported:\n• udp_mpegts → UDP MPEG-TS (recommended, stable for LAN/TVs)\n\nFuture support: SRT, HLS, RTMP.', max_length=20),
        ),
        migrations.AlterField(
            model_name='outputtarget',
            name='target_url',
            field=models.CharField(help_text='Full destination URL where the stream will be sent.\n\nExamples:\n• udp://192.168.1.29:5002   (LAN unicast)\n• udp://239.10.10.1:5000   (Multicast)\n\nAdvanced:\nYou may append query parameters such as:\n• pkt_size=1316\n• overrun_nonfatal=1\n\nExample:\nudp://239.10.10.1:5000?pkt_size=1316&overrun_nonfatal=1', max_length=500),
        ),
        migrations.AlterField(
            model_name='outputtarget',
            name='ttl',
            field=models.PositiveIntegerField(blank=True, help_text='Time-To-Live (TTL) for multicast packets.\n\n• 1 → local subnet only (recommended)\n• 2–5 → routed multicast\n\nUsed only for multicast addresses (239.x.x.x).', null=True),
        ),
    ]
